---
- name: "Example Playbook with Variables"
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    first_variable: "First variable"
    second_variable: "Second variable"
    version:
      - v1
      - v2
      - v3
    users:
      - user_1: maria
      - user_2: peter
      - user_3: sophie

  tasks:
    - name: "Display variables"
      ansible.builtin.debug:
        msg: "{{ first_variable }}, Versions: {{ version[1] }}, Users: {{ users[1].user_2 }}"

    - name: "Set variables"
      ansible.builtin.set_fact:
        print_result: "{{ second_variable }}, Versions: {{ version[0] }}, Users: {{ users[0].user_1 }}"

    - name: "Display seted variables"
      ansible.builtin.debug:
        msg: "{{ print_result }}"

    - name: "Include vars from file"
      ansible.builtin.include_vars:
        file: vars.yaml
        name: vars_from_file

    - name: "Display variables from vars file"
      ansible.builtin.debug:
        msg: "{{ vars_from_file.first_vars_variable }}, {{ vars_from_file.second_vars_variable }}"

    - name: "Display magic variables"
      ansible.builtin.debug:
        msg: "Playbook executed on {{ ansible_host }} {{ ansible_distribution }} at {{ ansible_date_time.time }}"

#    - name: "Display all magic variables"
#      ansible.builtin.debug:
#        msg: "Ansible fact is {{ ansible_facts }}"
