Vagrant.configure("2") do |config|
  # Используем проверенный box
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  # Увеличиваем таймаут
  config.vm.boot_timeout = 600
  
  # Отключаем синхронизацию папок для скорости
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Web Server 1
  config.vm.define "web1" do |web|
    web.vm.hostname = "web1.example.com"
    # Правильная настройка сети
    web.vm.network "private_network", ip: "192.168.56.10", type: "dhcp"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
      vb.name = "ansible-demo-web1"
      # Важная настройка!
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end
end
