---
- name: Configure deployed Vagrant VM
  hosts: all
  gather_facts: true
  become: true
  vars:
    preferred_webserver: "apache2"

    dev_packages:
      - git
      - curl
      - tree
      - htop

  tasks:
    - name: Install Apache (if selected)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: preferred_webserver == "apache2"

    - name: Install Nginx (if selected)
      ansible.builtin.apt:
        name: nginx
        state: present
      when: preferred_webserver == "nginx"

    - name: Install a set of development tools
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ dev_packages }}"

    - name: Create simple index.html
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Demo Site</title>
          </head>
          <body>
              <h1>Hello from Ansible!</h1>
              <p>Webserver: {{ preferred_webserver }}</p>
              <p>Host: {{ ansible_hostname }}</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart web server

    - name: Ensure Apache is started and enabled
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: true
      when: preferred_webserver == "apache2"

    - name: Ensure Nginx is started and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
      when: preferred_webserver == "nginx"

    - name: Show installation result
      ansible.builtin.debug:
        msg: |
          Successfully configured {{ preferred_webserver }} on {{ ansible_hostname }}
          Installed packages: {{ dev_packages | join(', ') }}

  handlers:
    - name: Restart web server
      ansible.builtin.systemd:
        name: "{{ preferred_webserver }}"
        state: restarted
