---
- name: Обновить кэш пакетов
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Установить базовые пакеты
  ansible.builtin.package:
    name:
      - curl
      - wget
      - vim
      - htop
    state: present

- name: Установить настроенный MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: Создать пользователя для демонстрации
  ansible.builtin.user:
    name: demo_user
    comment: "Demo User"
    groups: sudo
    append: true
    shell: /bin/bash
    state: present

- name: Убедиться, что пакет не установлен (демонстрация idempotency)
  ansible.builtin.package:
    name: telnet
    state: absent
